server:
 port: 8080

spring:
  datasource:
    url: jdbc:mysql://rm-2ze616301ae1654is2o.mysql.rds.aliyuncs.com:3306/gracie?characterEncoding=utf-8&useSSL=false
    username: root
    password: Mycs0314zc

mybatis:
  mapper-locations: mapper/*.xml